#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MusicPlayer.Resource", IsApplication=true)]

namespace MusicPlayer
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int arrow_left = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int border = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int border2 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int favorite_off = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int favorite_on = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int icon = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int pause = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int play = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int play_next = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int play_prev = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int repeat_all = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int repeat_off = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int repeat_one = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int search_icon = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int settings_icon = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int shuffle_off = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int shuffle_on = 2130837520;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050004
			public const int layoutstuff = 2131034116;
			
			// aapt resource value: 0x7f050001
			public const int linearLayout1 = 2131034113;
			
			// aapt resource value: 0x7f05000c
			public const int linearLayout2 = 2131034124;
			
			// aapt resource value: 0x7f05000a
			public const int linearLayout3 = 2131034122;
			
			// aapt resource value: 0x7f050003
			public const int musicList = 2131034115;
			
			// aapt resource value: 0x7f050012
			public const int musicSeekerBar = 2131034130;
			
			// aapt resource value: 0x7f050006
			public const int nowPlayingSongTitle = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int playMusicBackBtn = 2131034117;
			
			// aapt resource value: 0x7f050008
			public const int playMusicSetting = 2131034120;
			
			// aapt resource value: 0x7f050010
			public const int playNextBtn = 2131034128;
			
			// aapt resource value: 0x7f05000f
			public const int playPauseBtn = 2131034127;
			
			// aapt resource value: 0x7f05000e
			public const int playPrevBtn = 2131034126;
			
			// aapt resource value: 0x7f050011
			public const int repeatBtn = 2131034129;
			
			// aapt resource value: 0x7f05000d
			public const int shuffleBtn = 2131034125;
			
			// aapt resource value: 0x7f050009
			public const int songImage = 2131034121;
			
			// aapt resource value: 0x7f05000b
			public const int songTitleDisplay = 2131034123;
			
			// aapt resource value: 0x7f050013
			public const int sourceCodeLink = 2131034131;
			
			// aapt resource value: 0x7f050007
			public const int space1 = 2131034119;
			
			// aapt resource value: 0x7f050002
			public const int textView1 = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int toolbar1 = 2131034112;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int List_Music = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int PlayMusic = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
